name: univ3-ape

plugins:
  - name: alchemy
  - name: notebook
  - name: etherscan

default_ecosystem: ethereum

ethereum:
  default_network: mainnet
  mainnet:
    default_provider: alchemy

dependencies:
  - name: UniswapV3Core
    github: Uniswap/v3-core
    branch: main
